/**
 * FalconideAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Emailv1
 */
class Emailv1 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.apiKey = this.constructor.getValue(obj.apiKey || obj.api_key);
        this.emailDetails = this.constructor.getValue(obj.emailDetails || obj.email_details);
        this.xAPIHEADER = this.constructor.getValue(obj.xAPIHEADER || obj['X-APIHEADER']);
        this.settings = this.constructor.getValue(obj.settings);
        this.recipients = this.constructor.getValue(obj.recipients);
        this.attributes = this.constructor.getValue(obj.attributes);
        this.files = this.constructor.getValue(obj.files);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'apiKey', realName: 'api_key' },
            { name: 'emailDetails', realName: 'email_details', type: 'EmailDetails' },
            { name: 'xAPIHEADER', realName: 'X-APIHEADER', array: true },
            { name: 'settings', realName: 'settings', type: 'Settings' },
            { name: 'recipients', realName: 'recipients', array: true },
            { name: 'attributes', realName: 'attributes', type: 'Attributes' },
            { name: 'files', realName: 'files', type: 'Files' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Emailv1;
