/**
 * FalconideAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Settings
 */
class Settings extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.footer = this.constructor.getValue(obj.footer, true);
        this.clicktrack = this.constructor.getValue(obj.clicktrack, true);
        this.opentrack = this.constructor.getValue(obj.opentrack, true);
        this.unsubscribe = this.constructor.getValue(obj.unsubscribe, true);
        this.bcc = this.constructor.getValue(obj.bcc);
        this.attachmentid = this.constructor.getValue(obj.attachmentid);
        this.template = this.constructor.getValue(obj.template);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'footer', realName: 'footer' },
            { name: 'clicktrack', realName: 'clicktrack' },
            { name: 'opentrack', realName: 'opentrack' },
            { name: 'unsubscribe', realName: 'unsubscribe' },
            { name: 'bcc', realName: 'bcc' },
            { name: 'attachmentid', realName: 'attachmentid' },
            { name: 'template', realName: 'template' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Settings;
